[project]
name = "aurora-vault"
version = "1.0.2"
description = "Universal RAG engine"
authors = [
    { name = "Tareq", email = "tareqshah.027@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "platformdirs",
    "rich"
]
urls = { Homepage = "https://github.com/Tareq905/aurora-vault" }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["aurora_vault*"]

[tool.setuptools.package-data]
"aurora_vault.assets" = ["*.txt"]